steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mohamed-project-318217/nest-js-cloud-run-service:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mohamed-project-318217/nest-js-cloud-run-service:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'nest-js-cloud-run-service', '--region=us-central1', '--platform=managed', '--image=gcr.io/mohamed-project-318217/nest-js-cloud-run-service:$COMMIT_SHA']
